import type { Metadata } from 'next';
import './globals.css';
import Header from './Header';
import Footer from './Footer';

export const metadata: Metadata = {
  title: 'Next.js v13 Blog Example with TypeScript and Tailwind CSS',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="container mx-auto bg-slate-100">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
